package day41_Exceptions;

public class TryCatchBlocks {
    public static void main(String[] args) {

        System.out.println("Test started");

        System.out.println(9/0);

        System.out.println("Test completed");



    }
}
